import { Dimensions } from "react-native";

export const spacing = {
  xxxs: 4,
  xxs: 8,
  xs: 12,
  s: 16,
  m: 24,
  l: 32,
  xl: 40,
  xxl: 48,
  xxxl: 64,
  macro: 80,
  oneCent: "1%",
  TwoCent: "2%",
  fourCent: "4%",
  fiveCent: "5%",
  eightCent: "8%",
  twelveCent: "12%",
  sixteenCent: "16%",
  cent24: "24%",
  cent32: "32%",
  cent40: "40%",
  scH1cent: Dimensions.get("screen").height / 100,
  scH2cent: Dimensions.get("screen").height / 50,
  scH3cent: (Dimensions.get("screen").height * 3) / 100,
  scH4cent: Dimensions.get("screen").height / 25,
  scH5cent: Dimensions.get("screen").height / 20,
  scH6cent: (Dimensions.get("screen").height * 3) / 50,
  scH7cent: (Dimensions.get("screen").height * 7) / 100,
  scH8cent: (Dimensions.get("screen").height * 2) / 25,
  scH10cent: Dimensions.get("screen").height / 10,
  scH11cent: (Dimensions.get("screen").height * 11) / 100,
  scH12cent: (Dimensions.get("screen").height * 3) / 25,
  scH15cent: (Dimensions.get("screen").height * 3) / 20,
  scH16cent: (Dimensions.get("screen").height * 4) / 25,
  scH20cent: Dimensions.get("screen").height / 5,
  scH24cent: (Dimensions.get("screen").height * 6) / 25,
  scH32cent: (Dimensions.get("screen").height * 8) / 25,
  scH40cent: (Dimensions.get("screen").height * 2) / 5,
  scH50cent: Dimensions.get("screen").height / 2,
  scH70cent: (Dimensions.get("screen").height * 7) / 10,
  scW1cent: Dimensions.get("screen").width / 100,
  scW2cent: Dimensions.get("screen").width / 50,
  scW4cent: Dimensions.get("screen").width / 25,
  scW5cent: Dimensions.get("screen").width / 20,
  scW8cent: (Dimensions.get("screen").width * 2) / 25,
  scW12cent: (Dimensions.get("screen").width * 3) / 25,
  scW15cent: (Dimensions.get("screen").width * 3) / 20,
  scW16cent: (Dimensions.get("screen").width * 4) / 25,
  scW20cent: Dimensions.get("screen").width / 5,
  scW24cent: (Dimensions.get("screen").width * 6) / 25,
  scW28cent: (Dimensions.get("screen").width * 7) / 25,
  scW30cent: (Dimensions.get("screen").width * 3) / 10,
  scW32cent: (Dimensions.get("screen").width * 8) / 25,
  scW40cent: (Dimensions.get("screen").width * 2) / 5,
  scW50cent: Dimensions.get("screen").width / 2,
};
