export default {
  emailAddress: 'Enter Email',
  password: 'Enter Password',
  confirmPassword: 'Confirm Password',
  title: 'Login',
  loginButton: 'Login',
  signUpButton: 'SignUp',
  submitButton: 'Submit',
  modalButton: 'Ok',
  fullName: 'Full Name*',
  dob: 'Date Of Birth*',
  location: 'Location*',
  gender: 'Gender*',
  interest: 'Interest*',
  bioText: ' Bio* (other users will see this on your profile)*',
  bio: '',
  continue: 'Continue',
  forgotPassword: 'ForgotPassword',
  profileHeader: 'Complete Profile',
  terms: 'Terms and Condition',
  postDetail: 'Post Detail',
  name: 'Name',
  titlePost: 'Title',
  lorem: 'Lorem lipsum',
  loremDetail:
    "Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
  description: 'Description',
  search:'Search'
};
